### ISSUE TITLE
Dottorrent can not display fully on the screen

### ISSUE THREAD

**Issue by jjigoku** [kz26/dottorrent-gui#14] opened 2017-06-10 10:53 UTC
I use Antergos Gnome 3.24, full hd resolution, when i open dottorrent it does not show full at desktop

![image](https://user-images.githubusercontent.com/27810167/27002195-4c690cfc-4e05-11e7-99e8-369a1b4f31f2.png)

**Comment by kz26** [comment] 2017-06-10 20:52
Hmm, that's awkward. I guess some improvements will be needed for lower-resolution screens. What is your screen resolution?

**Comment by jjigoku** [comment] 2017-06-11 05:22
My resolution screen is 1920x1080 (16:9) 15inch

**Comment by kz26** [comment] 2017-06-13 15:29
OK, thanks. I'll look into this.

**Comment by jjigoku** [comment] 2017-06-13 15:37
Thanh you ^^

**Comment by jjigoku** [comment] 2017-06-14 13:57
Well, I forgot, I think the main reason for this is that I use 150% DPI, because if I put 100% DPI, the word too small is very difficult to see.

**Comment by kz26** [comment] 2017-06-14 22:06
That is what I suspected, since it works fine on my main monitor (which is also 1080p). I'm not a GUI expert, so I'll have to do some research to see what the best way to handle this would be (probably a scrollbar for the window area).

**Comment by jjigoku** [comment] 2017-06-15 01:28
Thank you very much ^^

**Comment by AdKiller** [comment] 2018-08-12 16:05
I have a similar problem. I have to maximize the window to see the create button, but the problem is as soon as I click the create button it goes out of view again and I have to resize the window to a smaller size, and maximize again, which is kind annoying.  It would be great if you could fix it.

OS Windows 10 Pro 1709 64-bit
v1.3.9
same result in 2 computers: 1366 x 768 and 1920 x 1080 resolutions 100% and 125% scales

**Comment by Pentaphon** [comment] 2019-04-16 23:55
@kz26 Any progress on this? The window behavior even resets itself to come off the screen when a torrent is created.

**Comment by kz26** [comment] 2019-04-19 18:21
Sorry, I've had limited time lately to work on this, but improved window sizing behavior is planned for the next release.

**Comment by kz26** [comment] 2019-04-20 22:02
This should be more or less remedied in the latest 1.3.11 release. Please let me know if there's any other issues - I'm closing this issue for now.

**Closed by kz26** 2019-04-20 22:02 UTC
Labels: enhancement

**Comment by AdKiller** [comment] 2019-04-24 08:12
@kz26 unfortunately v1.3.11 is not completely fixed for me.
Window position and maximize mode is not remembered at all. So the "create" button is often out of view at startup.

Windows 10 Pro 64bit 1803
